### ISSUE TITLE
Improve docs for version 0.8.95

### ISSUE THREAD

**Issue by antonsoroko** [pivotal-cf/docs-altoros-heartbeat#13]
Need to:

- "Bordify" (add a one pixel black border to) images that are lacking a border
- Review steps for incorrect formatting and thus mis-ordered numbers.
- Remove reference to Dingo PostgreSQL for PCF (this tile is obsolete)

(original - https://github.com/pivotal-cf/docs-altoros-heartbeat/pull/12#issuecomment-327632009)

I will create a PR for this issue later.

**Comment by jncd** [comment]
Hi @antonsoroko 
I think that @jknostman3 might have picked up these chores for you yesterday afternoon! I think you're good now and don't need to PR.

**Comment by antonsoroko** [comment]
@jknostman3 @jncd 

Thank you very much! I appreciate that!
